config/routes.rb
Rails.application.routes.draw do  
  resources :historicos, only: [:index] 
  resources :assunto_atendimentos
  root 'restrito/tela_agenda/atividades#index'
  resources :estatisticas, only: [:index] 
  resources :ferramentas_atendimento, only: [:index] 
  devise_for :admins
  resources :documentos, only: [:delete,:destroy,:update]
  resources :processos, only: [:delete,:destroy,:update,:index]
  resources :pessoas, only: [:delete,:destroy,:update]
  resources :advogados, only: [:delete,:destroy,:update]
  resources :telefones, only: [:delete,:destroy,:update]
  resources :contatos 
  resources :filiados, only: [:index, :edit,:delete,:destroy,:new,:show,:create,:update]
  namespace :restrito do
    namespace :tela_agenda do
      resources :atividades 
    end
  end
  resources :cadastro_atendimentos do 
    delete :delete_docs_attachment  
  end
  namespace :restrito do
    get 'ferramentas/index'
  end 
  namespace :restrito do
    get 'tela_consulta/index'
  end
  namespace :restrito do
    get 'tela_cadastro/index'
  end  
  namespace :restrito do
    get 'tela_agenda/index'
  end  
  namespace :restrito do
    get 'welcome/index' 
    get 'welcome/info' 
    get 'welcome/tutoriais' 
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :advogados_backoffice do
    get 'welcome/Cadastrar_Pessoas'
  end
  namespace :advogados_backoffice do
    get 'welcome/Cadastrar_Atendimento'
  end
  namespace :advogados_backoffice do
    get 'welcome/agenda'
  end
  namespace :site do
    get 'site/welcome/index'
  end 
end

app/models/advogado.rb
class Advogado < ApplicationRecord
  belongs_to :cadastro_atendimento  
end

app/controllers/advogados_controller.rb
class AdvogadosController < ApplicationController
  before_action :set_advogado, only: [:show, :edit, :update, :destroy]

  # GET /advogados
  # GET /advogados.json
  def index
    @advogados = Advogado.all
  end

  # GET /advogados/1
  # GET /advogados/1.json
  def show
  end

  # GET /advogados/new
  def new
    @advogado = Advogado.new
  end

  # GET /advogados/1/edit
  def edit
  end

  # POST /advogados
  # POST /advogados.json
  def create
    @advogado = Advogado.new(advogado_params)
    respond_to do |format|
      if @advogado.save
        format.html { redirect_to @advogado, notice: 'Advogado was successfully created.' }
        format.json { render :show, status: :created, location: @advogado }
      else
        format.html { render :new }
        format.json { render json: @advogado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advogados/1
  # PATCH/PUT /advogados/1.json
  def update
    respond_to do |format|
      if @advogado.update(advogado_params)
        format.html { redirect_to @advogado, notice: 'Advogado foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @advogado }
      else
        format.html { render :edit }
        format.json { render json: @advogado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advogados/1
  # DELETE /advogados/1.json
  def destroy
    @advogado.destroy
    respond_to do |format|
      format.html { redirect_to advogados_url, notice: 'Advogado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advogado
      @advogado = Advogado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def advogado_params
      params.require(:advogado).permit(:nome, :endereço, :cidade, :bairro, :cep, :telefone, :cidade, :email, :advogado, :oab, :telefone, :observação, :cadastro_atendimento_id,:update_objt, :usuario,:quem_username)
    end
end

app/helpers/advogados_helper.rb
module AdvogadosHelper
end

app/views/advogados/_form.html.erb
<%= form_with(model: advogado, local: true) do |form| %>
  <% if advogado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advogado.errors.count, "error") %> prohibited this advogado from being saved:</h2>

      <ul>
      <% advogado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereço %>
    <%= form.text_field :endereço %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :advogado %>
    <%= form.text_field :advogado %>
  </div>

  <div class="field">
    <%= form.label :oab %>
    <%= form.text_field :oab %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :observação %>
    <%= form.text_field :observação %>
  </div>

  <div class="field">
    <%= form.label :cadastro_atendimento_id %>
    <%= form.text_field :cadastro_atendimento_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advogados/edit.html.erb
<h1>Editing Advogado</h1>

<%= render 'form', advogado: @advogado %>

<%= link_to 'Show', @advogado %> |
<%= link_to 'Back', advogados_path %>

app/views/advogados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advogados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Cidade</th>
      <th>Bairro</th>
      <th>Cep</th>
      <th>Telefone</th>
      <th>Cidade</th>
      <th>Email</th>
      <th>Advogado</th>
      <th>Oab</th>
      <th>Telefone</th>
      <th>Observação</th>
      <th>Cadastro atendimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advogados.each do |advogado| %>
      <tr>
        <td><%= advogado.nome %></td>
        <td><%= advogado.endereço %></td>
        <td><%= advogado.cidade %></td>
        <td><%= advogado.bairro %></td>
        <td><%= advogado.cep %></td>
        <td><%= advogado.telefone %></td>
        <td><%= advogado.cidade %></td>
        <td><%= advogado.email %></td>
        <td><%= advogado.advogado %></td>
        <td><%= advogado.oab %></td>
        <td><%= advogado.telefone %></td>
        <td><%= advogado.observação %></td>
        <td><%= advogado.cadastro_atendimento %></td>
        <td><%= link_to 'Show', advogado %></td>
        <td><%= link_to 'Edit', edit_advogado_path(advogado) %></td>
        <td><%= link_to 'Destroy', advogado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advogado', new_advogado_path %>

app/views/advogados/new.html.erb
<h1>New Advogado</h1>

<%= render 'form', advogado: @advogado %>

<%= link_to 'Back', advogados_path %>

app/views/advogados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @advogado.nome %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @advogado.endereço %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @advogado.cidade %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @advogado.bairro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @advogado.cep %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @advogado.telefone %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @advogado.cidade %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advogado.email %>
</p>

<p>
  <strong>Advogado:</strong>
  <%= @advogado.advogado %>
</p>

<p>
  <strong>Oab:</strong>
  <%= @advogado.oab %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @advogado.telefone %>
</p>

<p>
  <strong>Observação:</strong>
  <%= @advogado.observação %>
</p>

<p>
  <strong>Cadastro atendimento:</strong>
  <%= @advogado.cadastro_atendimento %>
</p>

<%= link_to 'Edit', edit_advogado_path(@advogado) %> |
<%= link_to 'Back', advogados_path %>