config/routes.rb
Rails.application.routes.draw do  
  resources :historicos, only: [:index] 
  resources :assunto_atendimentos
  root 'restrito/tela_agenda/atividades#index'
  resources :estatisticas, only: [:index] 
  resources :ferramentas_atendimento, only: [:index] 
  devise_for :admins
  resources :documentos, only: [:delete,:destroy,:update]
  resources :processos, only: [:delete,:destroy,:update,:index]
  resources :pessoas, only: [:delete,:destroy,:update]
  resources :advogados, only: [:delete,:destroy,:update]
  resources :telefones, only: [:delete,:destroy,:update]
  resources :contatos 
  resources :filiados, only: [:index, :edit,:delete,:destroy,:new,:show,:create,:update]
  namespace :restrito do
    namespace :tela_agenda do
      resources :atividades 
    end
  end
  resources :cadastro_atendimentos do 
    delete :delete_docs_attachment  
  end
  namespace :restrito do
    get 'ferramentas/index'
  end 
  namespace :restrito do
    get 'tela_consulta/index'
  end
  namespace :restrito do
    get 'tela_cadastro/index'
  end  
  namespace :restrito do
    get 'tela_agenda/index'
  end  
  namespace :restrito do
    get 'welcome/index' 
    get 'welcome/info' 
    get 'welcome/tutoriais' 
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :advogados_backoffice do
    get 'welcome/Cadastrar_Pessoas'
  end
  namespace :advogados_backoffice do
    get 'welcome/Cadastrar_Atendimento'
  end
  namespace :advogados_backoffice do
    get 'welcome/agenda'
  end
  namespace :site do
    get 'site/welcome/index'
  end 
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  belongs_to :cadastro_atendimento
  validates :nome, :cidade, :email, :celular, :estado_civil,presence: true  
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)
    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update 
    @pessoa.update_objt = current_admin.email
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :profissao, :cep, :razao_social, :nome_fantasia, :cidade, :endereço, :cpf, :rg, :pis, :residencial, :comercial, :celular, :nacionalidade, :estado_civil, :estado_civil, :bairro, :email, :escolaridade, :insc_estadual, :insc_municipal, :responsável, :cnpj, :cadastro_atendimento_id,:update_objt, :usuario,:quem_username)
    end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :profissao %>
    <%= form.text_field :profissao %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :razao_social %>
    <%= form.text_field :razao_social %>
  </div>

  <div class="field">
    <%= form.label :nome_fantasia %>
    <%= form.text_field :nome_fantasia %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :endereço %>
    <%= form.text_field :endereço %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.number_field :rg %>
  </div>

  <div class="field">
    <%= form.label :pis %>
    <%= form.number_field :pis %>
  </div>

  <div class="field">
    <%= form.label :residencial %>
    <%= form.number_field :residencial %>
  </div>

  <div class="field">
    <%= form.label :comercial %>
    <%= form.number_field :comercial %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.number_field :celular %>
  </div>

  <div class="field">
    <%= form.label :nacionalidade %>
    <%= form.text_field :nacionalidade %>
  </div>

  <div class="field">
    <%= form.label :estado_civil %>
    <%= form.text_field :estado_civil %>
  </div>

  <div class="field">
    <%= form.label :estado_civil %>
    <%= form.text_field :estado_civil %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :escolaridade %>
    <%= form.text_field :escolaridade %>
  </div>

  <div class="field">
    <%= form.label :insc_estadual %>
    <%= form.text_field :insc_estadual %>
  </div>

  <div class="field">
    <%= form.label :insc_municipal %>
    <%= form.text_field :insc_municipal %>
  </div>

  <div class="field">
    <%= form.label :responsável %>
    <%= form.text_field :responsável %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="field">
    <%= form.label :cadastro_atendimento_id %>
    <%= form.text_field :cadastro_atendimento_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Profissao</th>
      <th>Cep</th>
      <th>Razao social</th>
      <th>Nome fantasia</th>
      <th>Cidade</th>
      <th>Endereço</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Pis</th>
      <th>Residencial</th>
      <th>Comercial</th>
      <th>Celular</th>
      <th>Nacionalidade</th>
      <th>Estado civil</th>
      <th>Estado civil</th>
      <th>Bairro</th>
      <th>Email</th>
      <th>Escolaridade</th>
      <th>Insc estadual</th>
      <th>Insc municipal</th>
      <th>Responsável</th>
      <th>Cnpj</th>
      <th>Cadastro atendimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.profissao %></td>
        <td><%= pessoa.cep %></td>
        <td><%= pessoa.razao_social %></td>
        <td><%= pessoa.nome_fantasia %></td>
        <td><%= pessoa.cidade %></td>
        <td><%= pessoa.endereço %></td>
        <td><%= pessoa.cpf %></td>
        <td><%= pessoa.rg %></td>
        <td><%= pessoa.pis %></td>
        <td><%= pessoa.residencial %></td>
        <td><%= pessoa.comercial %></td>
        <td><%= pessoa.celular %></td>
        <td><%= pessoa.nacionalidade %></td>
        <td><%= pessoa.estado_civil %></td>
        <td><%= pessoa.estado_civil %></td>
        <td><%= pessoa.bairro %></td>
        <td><%= pessoa.email %></td>
        <td><%= pessoa.escolaridade %></td>
        <td><%= pessoa.insc_estadual %></td>
        <td><%= pessoa.insc_municipal %></td>
        <td><%= pessoa.responsável %></td>
        <td><%= pessoa.cnpj %></td>
        <td><%= pessoa.cadastro_atendimento %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Profissao:</strong>
  <%= @pessoa.profissao %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @pessoa.cep %>
</p>

<p>
  <strong>Razao social:</strong>
  <%= @pessoa.razao_social %>
</p>

<p>
  <strong>Nome fantasia:</strong>
  <%= @pessoa.nome_fantasia %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @pessoa.cidade %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @pessoa.endereço %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @pessoa.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @pessoa.rg %>
</p>

<p>
  <strong>Pis:</strong>
  <%= @pessoa.pis %>
</p>

<p>
  <strong>Residencial:</strong>
  <%= @pessoa.residencial %>
</p>

<p>
  <strong>Comercial:</strong>
  <%= @pessoa.comercial %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @pessoa.celular %>
</p>

<p>
  <strong>Nacionalidade:</strong>
  <%= @pessoa.nacionalidade %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @pessoa.estado_civil %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @pessoa.estado_civil %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @pessoa.bairro %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pessoa.email %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @pessoa.escolaridade %>
</p>

<p>
  <strong>Insc estadual:</strong>
  <%= @pessoa.insc_estadual %>
</p>

<p>
  <strong>Insc municipal:</strong>
  <%= @pessoa.insc_municipal %>
</p>

<p>
  <strong>Responsável:</strong>
  <%= @pessoa.responsável %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @pessoa.cnpj %>
</p>

<p>
  <strong>Cadastro atendimento:</strong>
  <%= @pessoa.cadastro_atendimento %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>