config/routes.rb
Rails.application.routes.draw do  
  resources :historicos, only: [:index] 
  resources :assunto_atendimentos
  root 'restrito/tela_agenda/atividades#index'
  resources :estatisticas, only: [:index] 
  resources :ferramentas_atendimento, only: [:index] 
  devise_for :admins
  resources :documentos, only: [:delete,:destroy,:update]
  resources :processos, only: [:delete,:destroy,:update,:index]
  resources :pessoas, only: [:delete,:destroy,:update]
  resources :advogados, only: [:delete,:destroy,:update]
  resources :telefones, only: [:delete,:destroy,:update]
  resources :contatos 
  resources :filiados, only: [:index, :edit,:delete,:destroy,:new,:show,:create,:update]
  namespace :restrito do
    namespace :tela_agenda do
      resources :atividades 
    end
  end
  resources :cadastro_atendimentos do 
    delete :delete_docs_attachment  
  end
  namespace :restrito do
    get 'ferramentas/index'
  end 
  namespace :restrito do
    get 'tela_consulta/index'
  end
  namespace :restrito do
    get 'tela_cadastro/index'
  end  
  namespace :restrito do
    get 'tela_agenda/index'
  end  
  namespace :restrito do
    get 'welcome/index' 
    get 'welcome/info' 
    get 'welcome/tutoriais' 
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :advogados_backoffice do
    get 'welcome/Cadastrar_Pessoas'
  end
  namespace :advogados_backoffice do
    get 'welcome/Cadastrar_Atendimento'
  end
  namespace :advogados_backoffice do
    get 'welcome/agenda'
  end
  namespace :site do
    get 'site/welcome/index'
  end 
end

app/models/historico.rb
class Historico < ApplicationRecord
end

app/controllers/historicos_controller.rb
class HistoricosController < ApplicationController
  layout 'restrito'
  before_action :set_historico, only: [:show, :edit, :update, :destroy]

  # GET /historicos
  # GET /historicos.json
  def index
    if params[:email_hist] or params[:acao_hist] or params[:objt_hist] or params[:dat_hist]
      if params[:email_hist] != ''
        if params[:acao_hist] == 'Todos'
          if params[:objt_hist] == 'Todos'
            if params[:dat_hist] != ''
              @historicos =  Historico.where(quem: params[:email_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(quem: params[:email_hist]).page(params[:page]).per(20)
            end
          else
            if params[:dat_hist] != ''
              @historicos =  Historico.where(objeto: params[:objt_hist], quem: params[:email_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(objeto: params[:objt_hist], quem: params[:email_hist]).page(params[:page]).per(20)
            end
          end
        else
          if params[:objt_hist] == 'Todos'
            if params[:dat_hist] != ''
              @historicos =  Historico.where(acao: params[:acao_hist],objeto: params[:objt_hist], quem: params[:email_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(acao: params[:acao_hist],quem: params[:email_hist]).page(params[:page]).per(20)
            end
          else
            if params[:dat_hist] != ''
              @historicos =  Historico.where(acao: params[:acao_hist],objeto: params[:objt_hist], quem: params[:email_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(acao: params[:acao_hist],objeto: params[:objt_hist], quem: params[:email_hist]).page(params[:page]).per(20)
            end
          end 
        end
      else
        if params[:acao_hist] == 'Todos'
          if params[:objt_hist] == 'Todos'
            if params[:dat_hist] != ''
              @historicos =  Historico.where(hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.all.page(params[:page]).per(20)
            end
          else 
            if params[:dat_hist] != ''
              @historicos =  Historico.where(objeto: params[:objt_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(objeto: params[:objt_hist]).page(params[:page]).per(20)
            end
          end
        else
          if params[:objt_hist] == 'Todos'
            if params[:dat_hist] != ''
              @historicos =  Historico.where(acao: params[:acao_hist],objeto: params[:objt_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(acao: params[:acao_hist]).page(params[:page]).per(20)
            end
          else
            if params[:dat_hist] != ''
              @historicos =  Historico.where(acao: params[:acao_hist],objeto: params[:objt_hist],hracao: procura_data_hist,hrup: procura_data_hist).page(params[:page]).per(20)
            else 
              @historicos =  Historico.where(acao: params[:acao_hist],objeto: params[:objt_hist]).page(params[:page]).per(20)
            end
          end 
        end
      end
    else
      @historicos = Historico.page(params[:page]).per(20)
    end
    @local = 'Histórico'
  end
  def procura_data_hist
    Historico.all.each do |historico|
      if historico.created_at.strftime("%F") == params[:dat_hist]
        return historico.created_at.all_day
      end
    end
  end
  # GET /historicos/1
  # GET /historicos/1.json
  def show
  end

  # GET /historicos/new
  def new
    @historico = Historico.new
  end

  # GET /historicos/1/edit
  def edit
  end

  # POST /historicos
  # POST /historicos.json
  def create
    @historico = Historico.new(historico_params)

    respond_to do |format|
      if @historico.save
        format.html { redirect_to @historico, notice: 'Historico was successfully created.' }
        format.json { render :show, status: :created, location: @historico }
      else
        format.html { render :new }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historicos/1
  # PATCH/PUT /historicos/1.json
  def update
    respond_to do |format|
      if @historico.update(historico_params)
        format.html { redirect_to @historico, notice: 'Historico was successfully updated.' }
        format.json { render :show, status: :ok, location: @historico }
      else
        format.html { render :edit }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historicos/1
  # DELETE /historicos/1.json
  def destroy 
    @historico.destroy
    respond_to do |format|
      format.html { redirect_to historicos_url, notice: 'Historico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historico
      @historico = Historico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def historico_params
      params.require(:historico).permit(:usuarioudt, :acaoupdt, :hracao, :usuario, :acao_desc, :acao , :objeto,:quem,:hrup,:objeto_id,:quem_username)
    end
end

app/helpers/historicos_helper.rb
module HistoricosHelper
end

app/views/historicos/_form.html.erb
<%= form_with(model: historico, local: true) do |form| %>
  <% if historico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historico.errors.count, "error") %> prohibited this historico from being saved:</h2>

      <ul>
      <% historico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuarioudt %>
    <%= form.text_field :usuarioudt %>
  </div>

  <div class="field">
    <%= form.label :acaoupdt %>
    <%= form.text_field :acaoupdt %>
  </div>
  <div class="field">
    <%= form.label :hrup %>
    <%= form.datetime_select :hrup %>
  </div>
  <div class="field">
    <%= form.label :hracao %>
    <%= form.datetime_select :hracao %>
  </div>

  <div class="field">
    <%= form.label :usuario %>
    <%= form.text_field :usuario %>
  </div>

  <div class="field">
    <%= form.label :acao_desc %>
    <%= form.text_field :acao_desc %>
  </div>
  <div class="field">
    <%= form.label :acao %>
    <%= form.text_field :acao %>
  </div>
  <div class="field">
    <%= form.label :objeto %>
    <%= form.text_field :objeto %>
  </div>
  <div class="field">
    <%= form.label :quem %>
    <%= form.text_field :quem %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %> 

app/views/historicos/edit.html.erb
<h1>Editing Historico</h1>

<%= render 'form', historico: @historico %>

<%= link_to 'Show', @historico %> |
<%= link_to 'Back', historicos_path %>

app/views/historicos/index.html.erb
<div style="text-align:center">
  <div class="container body" style="text-align:center;font-size:18px">
    <div class="main_container" style="text-align:center"> 

      <!-- top navigation --> 
      <!-- page content --> 
      <div class="" style="text-align:center"> 

        <div class="clearfix"  style="text-align:center"></div>

        <div class="row" style="display: block;text-align:center"">
          <div class="col-md-6 col-sm-6  " style="width: 100%;margin-left: auto;margin-right: auto;text-align: center;">
            <div class="x_panel" style="text-align: center;width: 100%;font-family: Gilroy;margin-bottom: 47px;">
              <div class="x_title">
                <%= form_tag(historicos_path, method: :get) do %>
                  <div class="col-md-5 col-sm-5   form-group pull-right top_search" style="WIDTH: 100%;text-align:center">
                    <div class="input-group" > 
                      <h2 style="width: 100%;text-align: initial;font-family: Gilroy ExtraBold;">Histórico
                        <small style="float: right;text-align: end;margin-right: 2px;margin-top: 9px;width: 88%;font-size: 17px;">
                          Email: <%= text_field_tag 'email_hist', nil,type:'text', placeholder:"e-mail do usuario",style:"color: #000662;width: 30%;font-size: 20px;border-radius: 2px;background: #17598b54;border: 1px solid #26b99a;padding-left: 5px;"%>
                          Ação: <%= select_tag 'acao_hist', raw("<option>Todos</option><option>Excluiu</option><option>Atualizou</option><option>Adicionou</option>"), placeholder:"Ex: teste@teste.com", style:"padding-left: 5px;width: 13%;font-size: 20px;border-radius: 2px;background: #17598b54;border: 1px solid #26b99a;color: #000662;"%>
                          Objeto: <%= select_tag 'objt_hist', raw("<option>Todos</option><option>Contato</option><option>Telefone</option><option>Filiado</option><option>Atividade</option><option>Pessoa</option><option>Advogado</option><option>Processo</option><option>Documento</option><option>Atendimento</option>"),  style:"color: #000662;width: 12%;font-size: 20px;border-radius: 2px;background: #17598b54;border: 1px solid #26b99a; "%>
                          Dia: <%= text_field_tag 'dat_hist', nil, type:'date', placeholder:"Ex: teste@teste.com",  style:"width: 15%;font-size: 20px;border-radius: 2px;background: #17598b54;border: 1px solid #26b99a;padding-left: 5px;color:#000662"%>
                          <%= submit_tag "Consultar",  id:'btn_consulta_escuro', style:"font-size: 21px;"%></h3> 
                        </small>
                      </h2>
                    </div>
                  </div>
                <% end %>  
                <div class="clearfix"></div>
              </div>
              <div class="x_content" style="min-height:716px;text-align:center">
                <style>
                  .menu-btn {
                    background-color: #7e32d4;
                    color: white;
                    padding: 16px;
                    font-size: 20px;
                    font-weight: bolder;
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    border: none;
                  }
                  .dropdown-menu {
                    position: relative;
                    display: inline-block;
                  }
                  .menu-content {
                    display: none;
                    position: absolute;
                    background-color: #017575;
                    min-width: 160px;
                    z-index: 1;
                  }
                  .links {
                    color: rgb(255, 255, 255);
                    padding: 12px 16px;
                    text-decoration: none;
                    display: block;
                    font-size: 18px;
                    font-weight: bold;
                    border-bottom: 1px solid black;
                  }
                  .links:hover {
                    background-color: rgb(8, 107, 46);
                  }
                  .dropdown-menu:hover .menu-btn {
                    background-color: #3e8e41;
                  } 
                </style>

                <script>
                
                </script>
                <table class="table" id="historico"  style="width:100%;text-align:left">
                  <thead>
                    <tr>
                      <th>Usuário</th>
                      <th>E-mail</th>
                      <th style="text-align: initial;padding-left: 42px;width: 13%;">Ação</th>
                      <th style="text-align:center">Objeto</th> 
                      <th style="text-align:left">Data Hora</th> 
                      <th style="text-align:center">Acão</th> 
                      
                    </tr>
                  </thead>

                  <tbody class="historico" >
                    <% @historicos.each do |historico| %>
                      <div class="dropdown-menut_<%= historico.id %>">
                        <tr class="list">
                          <td style="text-align:left;width:18%"><%= historico.quem_username %></td>
                          <td style="text-align:left;width:18%"><%= historico.quem %></td>
                          <td>
                            <p id="hist_<%= historico.acao %>">
                            <%= historico.acao %>
                            </p>
                          </td>
                          <td style="text-align:center;width:10%"><%= historico.objeto %></td>
                          <td style="text-align:left;width:13%"><%= historico.hracao.strftime("%d/%m/%Y às %H:%M.") %></td>
                          <td style="width: 1%;text-align: center;" class="td_btn"><a class="menu-btn_<%= historico.id %>"><i class="fa fa-eye" id="btn_hist"style="color:#385bc2"></i></a></td>  
                        </tr>  
                      </div> 
                        <tbody class="menu-content_<%= historico.id %>" style="display: none;z-index: 1;width: max-content;"> 
                          <tr style="border:1px solid black;">
                            <td colspan="7"><li>Descrição do(a) <%= historico.objeto %>.</li></td> 
                          </tr>  
                          <tr style="border:1px solid black;">
                            <td style="text-align:left;padding-left: 47px;" colspan="4">Descrição Inicial: <%= historico.acao_desc %>.</td> 
                            <td style="text-align:left;width:13%"><%= historico.hracao.strftime("%d/%m/%Y às %H:%M.") %></td>
                            <td style="text-align:left;width: 1%;"></td> 
                          </tr> 
                          <tr style="border:1px solid black;">
                            <td style="text-align:left;padding-left: 47px;" colspan="4">Descrição Atual: <%= historico.acaoupdt %>.</td>  
                            <td style="text-align:left;width:13%"><%= historico.hrup.strftime("%d/%m/%Y às %H:%M.") %></td>
                            <td style="text-align:left;width: 1%;"></td> 
                          </tr>
                          <tr>
                            <td colspan="4"><hr style="border: 0px solid #29716d;background: #c1d5d5;height: 1px;"></td> 
                            <td colspan="2" style="font-size: 17px;text-align: center;color: #172d43;font-family: Gilroy ExtraBold;background: #ffffff38;box-shadow: 0px 0px 3px #29716e;border-radius: 18px;">Histórico Id: <%= historico.id %></td>
                          </tr>
                        </tbody>
                      <script>
                        let dropdownBtn_<%= historico.id %> = document.querySelector('.menu-btn_<%= historico.id %>');
                        let menuContent_<%= historico.id %> = document.querySelector('.menu-content_<%= historico.id %>');
                        dropdownBtn_<%= historico.id %>.addEventListener('click',()=>{
                          if(menuContent_<%= historico.id %>.style.display==="none"){
                              menuContent_<%= historico.id %>.style.display="contents";
                          } else {
                              menuContent_<%= historico.id %>.style.display="none";
                          }
                        })
                      </script>
                    <% end %> 
                  </tbody>
                </table> 
                  <div style="float: none;display: flow-root;">
                    <%= paginate @historicos,style:"text-align:center"%>
                  </div>
              </div>
            </div>        
          </div> 
          <div class="clearfix"></div> 
        </div>
      </div> 
    </div>
  </div>  
</div>

app/views/historicos/new.html.erb
<h1>New Historico</h1>

<%= render 'form', historico: @historico %>

<%= link_to 'Back', historicos_path %>

app/views/historicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuarioudt:</strong>
  <%= @historico.usuarioudt %>
</p>

<p>
  <strong>Acaoupdt:</strong>
  <%= @historico.acaoupdt %>
</p>
<p>
  <strong>Hracao:</strong>
  <%= @historico.hrup %>
</p>
<p>
  <strong>Hracao:</strong>
  <%= @historico.hracao %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @historico.usuario %>
</p>

<p>
  <strong>Acao:</strong>
  <%= @historico.acao_desc %>
</p>
<p>
  <strong>Acao:</strong>
  <%= @historico.acao %>
</p>
<p>
  <strong>Acao:</strong>
  <%= @historico.objeto %>
</p>
<p>
  <strong>Acao:</strong>
  <%= @historico.quem %>
</p>
<%= link_to 'Edit', edit_historico_path(@historico) %> |
<%= link_to 'Back', historicos_path %>